name: Go Build and Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Verify modules
      run: go mod verify

    - name: Test
      run: go test -v ./...

    - name: Build
      run: |
        mkdir bin
        make build

    - name: Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/aws-assume-role-linux
          bin/aws-assume-role-osx
          bin/aws-assume-role-osx-arm
